version: "3.3"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: connector-web
        working_dir: /home/www/
        volumes:
            - ./:/home/www

    nginx:
        image: nginx:alpine
        ports:
            - 8000:8000
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d/
